# Generated by Django 3.0 on 2019-12-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_auto_20191210_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='estado',
            field=models.CharField(max_length=1),
        ),
    ]
