# Generated by Django 3.0 on 2019-12-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0003_auto_20191210_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flor',
            options={'verbose_name': 'Flor', 'verbose_name_plural': 'Flores'},
        ),
    ]
