# Generated by Django 3.0 on 2019-12-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0005_flor_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='fotografia',
            field=models.ImageField(null=True, upload_to='flores'),
        ),
    ]
