# Generated by Django 3.0 on 2019-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0006_auto_20191210_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('nombreflor', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
